CREATE TABLE users
(
    id       BIGINT PRIMARY KEY,
    username VARCHAR(255),
    password VARCHAR(255)
);
CREATE SEQUENCE USER_ID_SEQ START WITH 10;
ALTER TABLE users
    ALTER COLUMN ID SET DEFAULT nextval('USER_ID_SEQ');